micronaut:
  executors:
    io:
      type: fixed
      nThreads: 10
  application:
    name: mn-schedulers
  server:
    maxRequestSize: 1MB
    host: localhost
    netty:
      maxHeaderSize: 500KB
      worker:
        threads: 1
      parent:
        threads: 1
      childOptions:
        autoRead: true
---
consul:
  client:
    registration:
      enabled: false
